{
	'name': 'Universal Car Rental HR',
	'version': '0.1',
	'category': 'Human Resources',
	'description': """
		Custom implementation for PT. Universal Car Rental Jakarta
	""",
	'author': 'Christyan Juniady and Associates',
	'maintainer': 'Christyan Juniady and Associates',
	'website': 'http://www.chjs.biz',
	'depends': [
		"base","board","web",
		"chjs_custom_view","chjs_region",
		"hr","hr_recruitment","hr_contract","hr_attendance","hr_holidays","hr_expense","hr_payroll",
		"hr_recruitment_period","hr_recruitment_requirement","hr_employee_family","hr_employee_health",
		"document_approval",
		"hr_termination","hr_overtime","fleet"
	],
	'sequence': 150,
	'data': [
		'security/universal_security.xml',
		'security/ir.model.access.csv',
		'data/hr.department.csv',
		'data/hr.job.csv',
		'data/hr_recruitment.xml',
		'data/hr_employee.xml',
		'data/hr_contract.xml',
		'views/universal.xml',
		'views/chjs_region.xml',
		'views/hr_recruitment.xml',
		'views/hr_employee.xml',
		'views/hr_contract.xml',
		'views/hr_attendance.xml',
		'views/hr_holidays.xml',
		'views/hr_expense.xml',
		'views/hr_recruitment.xml',
		'views/hr_recruitment_period.xml',
		'views/hr_termination.xml',
		'views/hr_payroll.xml',
		'views/res_config.xml',
		'menu/universal_menu.xml',
		'report/report_universal.xml',
		'report/report_contract_driver.xml',
		'report/report_contract_emp_trial.xml',
		'report/report_contract_employee.xml',
		'report/report_contract_attachment.xml',
		'cron/hr_employee.xml',
		'cron/hr_recruitment.xml',
		'cron/hr_contract.xml',
		'cron/hr_holidays.xml',
	],
	'demo': [
	],
	'test': [
	],
	'installable': True,
	'auto_install': False,
	'qweb': [
	]
}
